### ISSUE TITLE
1.7.x docker image not working

### ISSUE THREAD

**Issue by sebthom** [ltb-project/self-service-password#1045]
when upgrading from the docker image from 1.6.1 to 1.7.0 or 1.7.2 the UI is not displayed anymore and I see the following error message in the log:
```
[Mon Jan 27 11:31:57.166882 2025] [mpm_prefork:notice] [pid 7:tid 7] AH00163: Apache/2.4.62 (Debian) PHP/8.3.11 configured -- resuming normal operations
[Mon Jan 27 11:31:57.166967 2025] [core:notice] [pid 7:tid 7] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Jan 27 11:32:06.360693 2025] [php:warn] [pid 18:tid 18] [client 10.0.0.58:51706] PHP Warning:  require_once(../conf/config.inc.php): Failed to open stream: No such file or directory in /var/www/htdocs/index.php on line 11
[Mon Jan 27 11:32:06.360816 2025] [php:error] [pid 18:tid 18] [client 10.0.0.58:51706] PHP Fatal error:  Uncaught Error: Failed opening required '../conf/config.inc.php' (include_path='.:/usr/local/lib/php') in /var/www/htdocs/index.php:11\nStack trace:\n#0 {main}\n  thrown in /var/www/htdocs/index.php on line 11
```

So PHP complains that `/var/www/conf/config.inc.php` does not exist. When I SSH into the container I can see that this file isn't there and only a file `/var/www/config.inc.php.orig` is present.

I am using the container in swarm like this:
```yaml
  self_service_password:
    image: ltbproject/self-service-password # https://hub.docker.com/r/ltbproject/self-service-password
    secrets: [ secrets.sh ]
    entrypoint: /bin/sh -c ". /run/secrets/secrets.sh && docker-php-entrypoint apache2-foreground"
    #environment:
      # loaded via /run/secrets/secrets.sh
      #SSP_LDAP_USER_PASSWORD:
      #SSP_TOKEN_KEYPHRASE:
    volumes:
      - ${DATA_ROOT}/self-service-passsword/ssp.conf.php:/var/www/conf/config.inc.local.php
```
