### ISSUE TITLE
documentation for docker

### ISSUE THREAD

**Issue by r2evans** [ltb-project/self-service-password#408]
@coudot thank you for #52!

I don't know if there are plans for documentation (sample aux files) for it, but some suggestions:

- sample `docker-compose.yml` file that demonstrates combinations of options: local config and docker secrets
    
    ```yml
    version: '3.7'
    services:
       ssp:
         image: ssp
         volumes:
           - /srv/ssp/config.inc.local.php:/var/www/html/ssp/conf/config.inc.local.php:ro
           - /srv/ssp/custom:/var/www/html/ssp/custom:ro
         secrets:
           - smtp_password
           - ldapadmin_password
    secrets:
      smtp_password:
        file: local/path/to/secrets/smtp_password
      ldapadmin_password:
        file: local/path/to/secrets/ldapadmin_password
    ```

- sample `config.inc.local.php` that supports docker secrets (with `file_get_contents()`); for instance

    ```php
    <?php
    
    $ldap_url = 'ldap://myad.host.com';
    $ldap_binddn = 'realm\administrator';
    $ldap_bindpw = file_get_contents('/run/secrets/ldapadmin_password');
    $ldap_base = 'cn=Users,dc=myad,dc=host,dc=com';
    $ldap_login_attribute = 'sAMAccountName';
    $ldap_filter = "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))";
    
    $samba_mode = true;
    $ad_mode = true;
    
    $pwd_min_length = 10;
    $pwd_min_lower = 1;
    $pwd_min_upper = 1;
    $pwd_min_digit = 1;
    $pwd_special_chars = '"!@#$%^-_=+"';
    $pwd_show_policy = 'always';
    $pwd_show_policy_pos = 'above';
    $use_change = false;
    $use_questions = false;
    
    $mail_attribute = 'mail';
    $mail_from = 'somebody@host.com';
    $mail_from_name = 'Self Service Password';
    $mail_smtp_host = 'some.mailhost.com';
    $mail_smtp_auth = true;
    $mail_smtp_user = 'somebody@host.com';
    $mail_smtp_pass= file_get_contents('/run/secrets/smtp_password');
    $mail_smtp_port = '587';
    $mail_smtp_secure = 'startssl';
    
    $use_sms = false;
    $keyphrase = 'qwer1234';
    $reset_url = 'https://www.host.com/ssp/index.php';
    $logo = 'custom/something.png';
    $background_image = 'custom/something_else.jpg';
    $default_action = 'sendtoken';
    $obscure_failure_messages = array("nomatch","passworderror","sshkeyerror","mailnomatch","tokenattempts");
    ```

- helm or k8s examples? (I have none, sorry)
