### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by thiagoalmeidasa** [ltb-project/self-service-password#52]
Would you be interested in having a Dockerfile?

Would you be interested in having an official docker image?

Check it: https://github.com/moss-it/docker-selfservicepassword

**Comment by coudot** [comment]
Hi, this is really cool, thank you!

Don't you think you can use directly Debian packages?

And could we alos have an embedded LDAP directory so we could provide a working demonstration?

**Comment by r2evans** [comment]
Because embedding a full LDAP directory within the image would add a bit (in MB, in packages, in Ports to expose, perhaps in Volumes to expose, I suggest a working demo could be a different Dockerfile that starts from (inherits) the base SSP image. This keeps the base SSP image relatively minimal (mostly for security and simplicity).

**Comment by coudot** [comment]
Indeed, we should use Docker compose or something like this to have an LDAP container next to SSP container.

**Comment by thiagoalmeidasa** [comment]
That's an example of working `docker-compose.yml`:

```yaml
version: '2'

services:
  web:
    image: nginx:latest
    hostname: selfservicepassword.example.com
    volumes_from:
      - php
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: moss/self-service-password
    hostname: selfservicepassword.example.com
    env_file: .env
  openldap:
    image: osixia/openldap:1.1.6
    hostname: openldap.example.com
    environment:
      - LDAP_ORGANISATION='Example'
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=supersecurepassword
      - LDAP_CONFIG_PASSWORD=configpassword
    command: "--loglevel debug"
```

Could you evaluate this approach and give me some feedback?
I'm already using my SSP docker image in production with my openldap service and it's working perfectly.
